### ISSUE TITLE
Migration file workflow when deploying

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool-cli#173]
_TBD_

**Comment by timsuchanek** [comment]
# Proposal for Migration file workflow
## Migration Files
### Filenames
A new file called `migration.yml` will be created. The last migration will be renamed to `migration.prev.yml`, so the last migration is always available in `migration.prev.yml`.
Later we want to show migrations in the Console Dashboard, so users have an easier overview of which migrations have been executed.

### File Content
```yaml
migrationValues:
  - field: User.age
    value: "18"
  - field: Post.description
    value: "No description"

rename:
  - oldName: User.aage
    newName: User.age
  - oldName: Post.desscription
    newName: Post.description
```

## Command Workflow
### deploy
When the deploy command is executed, the server tells the CLI if a migrationValue is required.
If that is the case, the CLI creates a template for the `migrationValues` and prompts the user to create migrationValues:
```sh
$ graphcool deploy
Deploy to project my-project...

Due to the changes in `types.graphql` you need to provide migration values.
A file called `migration.yml` has just been created with the following template:

migrationValues:
  - field: User.age
    value: ""

Please fill in a suiting migration value and run `graphcool deploy` again.
```

### diff
Same messages as in deploy:
```sh
$ graphcool deploy
Calculating diff of local and remote project definition...

Here are all the local changes:

  | (+)  A new type with the name `Post` is created.
  ├── (+)  A new field with the name `description` and type `String!` is created.

Due to the changes in `types.graphql` you need to provide migration values.
A file called `migration.yml` has just been created with the following template:

migrationValues:
  - field: User.age
    value: ""

Please fill in a suiting migration value to unblock the `graphcool deploy` command.
```
