### ISSUE TITLE
Only changing env vars is not registered for deploy

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-cli#244]
I want to update env vars and deploy that change. However, only changing the env vars returns the message

```
Identical project definition for project <id> in env dev, no action required.
```

Reproduction:

```yaml
functions:
  testErrors:
    handler:
      code:
        src: ./code/testErrors.js
    type: resolver
    schema: ./schemas/testErrors.graphql
```

add environment:

```yaml
functions:
  testErrors:
    handler:
      code:
        src: ./code/testErrors.js
    type: resolver
    schema: ./schemas/testErrors.graphql
    environment:
      CLIENT_ID: ${env:CLIENT_ID}
      CLIENT_SECRET: ${env:CLIENT_SECRET}
```

and deploy.

**Comment by marktani** [comment]
The problem was that I used a wrong syntax:

```yaml
functions:
  testErrors:
    handler:
      code:
        src: ./code/testErrors.js
        environment:
          CLIENT_ID: ${env:CLIENT_ID}
          CLIENT_SECRET: ${env:CLIENT_SECRET}
    type: resolver
    schema: ./schemas/testErrors.graphql
```
