### ISSUE TITLE
Diff does not work when moving function files

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-cli#256]
I changed this function

```yml
functions:
  hello:
    handler:
      code:
        src: ./code/hello.js
    type: resolver
    schema: ./code/hello.graphql

```

to this, while also moving the files accordingly:

```yml
functions:
  hello:
    handler:
      code:
        src: ./src/hello.js
    type: resolver
    schema: ./src/hello.graphql
```

Note `./code/` -> `./src/`. When I now do `graphcool diff`, I get this error message:

```
The following errors occured while reading the graphcool.yml project definition:
  The file ./code/hello.js for function hello does not exist
  The file ./code/hello.js for the schema extension of function hello does not exist
```

It should be detected that both `graphcool.yml` and the functions have been adjusted accordingly, and the diff should be printed.
